# Generated by Django 5.2 on 2025-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complainer_id', models.BigIntegerField()),
                ('target_type', models.SmallIntegerField()),
                ('target_id', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'complaint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_id', models.BigIntegerField(default=0)),
                ('target_type', models.SmallIntegerField(default=0)),
                ('reviewer_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=100)),
                ('ban_type', models.CharField(max_length=100)),
                ('ban_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'complaint_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField()),
                ('event', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
