# Generated by Django 5.2 on 2025-09-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainer_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='target_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='complaintreview',
            name='reviewer_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='complaintreview',
            name='target_id',
            field=models.UUIDField(),
        ),
    ]
