# Generated by Django 5.2 on 2025-09-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_complainer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintreview',
            name='target_id',
            field=models.UUIDField(),
        ),
    ]
