
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint-service
  labels:
    app: complaint-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaint-service
  template:
    metadata:
      labels:
        app: complaint-service
    spec:
      containers:
      - name: complaint-service
        image: complaint-service:latest
        imagePullPolicy: Never  # 在 CI/CD 中会被更新
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_ENGINE
          value: "django.db.backends.mysql"
        - name: DB_NAME
          value: "cfmp-user"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_HOST
          value: "complaint-db-service"
        - name: DB_PORT
          value: "3306"
        - name: DEBUG
          value: "True"
        - name: SECRET_KEY
          value: "123"
        - name: NODE_PORT
          value: "30008"
        - name: NODE_IP
          value: "101.132.163.45"


---
apiVersion: v1
kind: Service
metadata:
  name: complaint-service
  labels:
    app: complaint-service
spec:
  selector:
    app: complaint-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaint-db
  template:
    metadata:
      labels:
        app: complaint-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "cfmp-complaint"
        - name: MYSQL_ROOT_HOST      # 添加这一行
          value: "%"                 # 允许 root 从任何主机连接
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysql -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 5

      volumes:
      - name: mysql-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: complaint-db-service
spec:
  selector:
    app: complaint-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP